### ISSUE TITLE
Provide construction details for ring 148 (Ram's Ore extension ring)

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#16]
https://github.com/rschwiebert/dart_data/blob/90f76e76f8c44e2f14c632379de8e7a7c92deedb/db/ringapp/ring/RING_000148/data.yaml#L5

[Visit the ring page](https://ringtheory.herokuapp.com/rings/ring/148/) for sources to draw information from.

**Comment by dyunov** [comment]
New description: Let $K$ be an infinite field, $S = K[\ldots, x_{-1}, x_0, x_1, \ldots]$, $I = ( \{ x_k x_{k + a} x_{k + 2a}: k \in \Bbb Z, a \in \Bbb Z \setminus \{0\} \} )$ an ideal of $S$, and $\sigma$ the $K$-automorphism of $S$ such that $\sigma(x_i) = x_{i + 1}$ for all $i$. Then, $\sigma$ induces a $K$-automorphism of $R = S/I$. Ram's Ore extension ring $T$ is the skew polynomial ring $R[x; \sigma]$.

Would you like to specialize $K$ to say $\Bbb Q$, or any other one? Many properties don't depend on $K$ here. Marks and Lam (p167) don't impose the cardinality condition on $K$; Ram needed it to be infinite to have $R$ semisimple (for primeness of $T$ it is not necessary).

Properties (part I)
---
Suppose $e = \sum \alpha_i x^i \in T$ is an idempotent. Take the lowest $i$ with $\alpha_i \not = 0$. But then, if $i > 0$, each of the terms in the expansion of $e^2$ is either zero or is a multiple of $x^{2i}$. Thus all idempotents of $T$ lie in $R$.
For similar reasons one deduces that 1) an idempotent in $R$ has constant term $0$ or $1$ (you can't get a number by multiplying terms that contain letters), and finally 2) $R$ is strongly connected.

<details><summary>Some properties</summary>

- :x: I_0. $x_0 T \not \subset J(T)$, as $1 + x_0$ is not invertible (the inverse would also have to lie in $R$, and then be equal to $\sum (-1)^n x_0^n$, which is not available there).
- :x: $\pi$-regular. For any $y \in T$ each term of the product $x_0^n y x_0^n$ is either zero, or of length at least $2n$.
- ✔️ Abelian.
- :x: Baer. Too few idempotents for (7.45) in Lam II to hold.
- ✔️ anti-automorphic. $\sigma$ seems to be an anti-automorphism if I'm not lost in the definitions.
- :x: clean. $1+x_0$ and $x_0$ are not units.
- ✔️ compressible.
- ❔ countable. Whenever $K$ is.
- :x: exchange. Take $(1+x_0) + (-x_0)$.
- :x: finite. The set $\{x_0^n\}$ is infinite.
- :x: fully prime. $(x_0 x_1)$ is not prime.
- ✔️ lift/rad.
- :x: local. $(1+x_0)$ and $(-x_0)$ are not invertible and have an invertible sum.
- ✔️ orthogonally finite.
- :x: simple. $x_1 \not \in T x_0 T$.
- :x: strongly $\pi$-regular. $\{x_0^n T\}$ does not terminate.
- :x: von Neumann regular. $x_0 \not \in x_0 T x_0$.
- :x: L/R ACC annihilator. $l(x_1) \supset l(x_1 x_2) \supset l(x_1 x_2 x_4) \supset \ldots$ and symmetrically.
- :x: L/R Bezout. $(x_0, x_1)$ is not cyclic.
- :x: L/R DCC annihilator. See above.

</details>

Additional comments
---
GitHub's Markdown won't show `\{` and `\}` in my formulae.
I wonder what one can say about $J(T)$.
The ring might be Armendariz and unlikely to have stable range 1.
I'll go through the remaining asymmetric properties later (hence the "part I").

@rschwiebert Have you considered adding a search page for the *text* content? While compiling the list I stumbled upon a familiar-sounding property that was defined as *"Noetherian and self-injective"* and decided to put it aside until I get to the finiteness conditions. A Google search over the site gave abysmally unrelated results, even though the phrase in italics appears exactly in this form on the QF page.

**Comment by rschwiebert** [comment]
@dyunov Regarding the text content search page: I think that's a great idea, but I don't have good ideas how to do it.  You are thinking mainly of the properties, yes?  What if, as a first approximation, there were a page that just listed all the definitions, so one could Ctrl-F stuff?  I would greatly appreciate if you opened an issue as a feature request for something like this.

**Comment by rschwiebert** [comment]
> Maybe add the right Ore condition to the property page? Are Ore extensions related to the Ore condition?
Those both are already there: [Ore domain](https://ringtheory.herokuapp.com/properties/property/69/) [Ore ring](https://ringtheory.herokuapp.com/properties/property/94/)

I don't know the detailed history of Ore extensions but I surmise Ore must have made use of them. You can build Ore domains using Ore extension [that are not right Ore](http://ringtheory.herokuapp.com/rings/ring/21/), though.

**Comment by dyunov** [comment]
> You are thinking mainly of the properties, yes?

Currently even the obscure ring entry names are way more descriptive than some property names, so for now, yes. An automatically-generated full list of properties with definitions would be a good start, maybe something like:

- [$I_0$](https://ringtheory.herokuapp.com/properties/property/48/): Every right ideal not contained in $J(R)$ contains a nonzero idempotent. Also called "semipotent"
- [$\pi$-regular](https://ringtheory.herokuapp.com/properties/property/46/): For all $a$ in $R$ there exists an $x\in R$ and a natural number $n$ such that $(a^n)x(a^n)=a^n$
- $\ldots$
Then it should probably be linked to at the top of the [full property list](https://ringtheory.herokuapp.com/properties/).

> Those both are already there

I know, I meant add the "formula" as stated in Lam II (10.3, pp300–303): $aS \cap sR \not = \varnothing$, where $S$ is the set of regular elements; or the "classical" per-element variant like at the end of [Application section](https://en.wikipedia.org/wiki/Ore_condition#Application) on Wikipedia to the property page.
Sorry for poor wording and thanks for the example!

**Comment by rschwiebert** [comment]
Is example 3.2 supposed to show necessity of the annihilator condition mentioned in Theorem 2.1?  Theorem 2.1 says if $R$ is semiprime then $R_\sigma[x]$ is semiprimitive. But example 3.2 is not semiprimitive (it has nonzero Levitzki radical, and I think that's contained in the Jacobson radical) but R is claimed to be semiprimitive and so it should also be semiprime.  So i guess one can only conclude that $R$ does not have the ACC on left annihilator ideals.

**Comment by dyunov** [comment]
Yes, the purpose of Ex3.2 seems to be exactly that.
$R$, which is commutative, doesn't satisfy ACC on annihilators of elements (for some reason I inverted the $\subset$'s in that part of my comment), and therefore neither does $R_\sigma[x]$.

**Comment by rschwiebert** [comment]
Since much relies on the establishments of the idempotents in Ring 148, I'd like to formally flesh out the details here.

### Claim 1: The coefficient ring $\mathbb Q[\{x_i\mid i\in \mathbb Z\}]/I$ where $I$ is the set of monomial triples in arithmetic progression has only trivial idempotents.
_Proof_:  The set of monomials in $\{x_i\mid i\in \mathbb Z\}$ carries a standard monomial order: the powers of the $x_i$ can be ordered lexicographically so that monomial $m_1$ is greater than monomial $m_2$ if, when listing their complete sets of exponents, which are lists of natural numbers indexed by $\mathbb Z$ having finite support, the largest index $z$ on which either one is nonzero has a higher exponent for $m_1$ than $m_2$ has.  

This monomial ordering is compatible with multiplication in $\mathbb Q[\{x_i\mid i\in \mathbb Z\}]$ but needs a little adaptation for the quotient.  In the quotient, the monomial ordering is no longer "compatible" with the multiplication because some of the products may be zero.  However, we can still say that for two nonempty monomials $m_1, m_2$, either $m_1 < m_1m_2$ in the monomial order OR $m_1m_2=0$ (I say the empty monomial is the one with exponents all zero, which is just $1$.)  Now, given an element $e=\alpha_0+\sum_{m \text{ monomial }} \alpha_mm$ of the quotient ring, it's clear that the only contributor to the constant term of $e^2$ is simply $\alpha_0^2$, and considering that $\mathbb Q$ is a field, this implies $\alpha_0\in\{0,1\}$.

If $\alpha_0=0$, then it's clear that the least-ordered term cannot be obtained as a sum of products of the other monomials. The result of any such multiplication has degree strictly greater than the least, or else the product yields zero.

If $\alpha_0=1$, the only contributor to the minimal monomial $m$ is $2m$, and since the field is not characteristic $2$, that would imply $m=0$, a contradiction.  This establishes that $R=\mathbb Q[\{x_i\mid i\in \mathbb Z\}]/I$ only has trivial idempotents.

Moving on to $R[x;\sigma]$, we apply an ordinary degree argument.  Because $\sigma$ is injective, the degree of a product is going to be the sum of the degrees of the things being multiplied.
We consider an element $e=\sum_{i=0}^n \alpha_i x^i$. It's clear that $\alpha_0$ must be an idempotent of $R$, which we have established only has trivial idempotents $0$ and $1$.

If $\alpha_0=0$, it is easy to see that the lowest degree of $x$ in $e^2$ is strictly greater than that of the lowest degree in $e$, so $e^2=e$ is not possible.

Finally suppose $\alpha_0=1$, and let $i$ be the least index greater than $0$ such that $\alpha_i\neq 0$.  Clearly in the product $e^2$ the coefficient of $x^i$ is given by $2\alpha_ix^i$, as all other distributed products have higher degrees.  Since the characteristic of $\mathbb Q$ is not 2, we conclude that $\alpha_i=0$, a contradiction.  This establishes that $R[x;\sigma]$, ring 148, also only has trivial idempotents.

**Comment by rschwiebert** [comment]
(With $T$ the commutative quotient ring and $R=T[x;\sigma]$)

@dyunov  I feel confident about all the properties you mentioned except these:
R IS anti-automorphic ($\sigma$ is not defined on all of $R$.)
R IS lift-rad (why? I'm not sure what J(R) is, although it seems it must be contained within $(x)$.)
R IS NOT Ikeda-nakayama: (From where you left off, you'd have to show ann(x_0x_1R)+ann(x_1x_2R)\neq R, which isn't clear to me.  The left annihilators of course do not contain units, but their sum possibly could?)
R IS NOT cohopfian: (It's not clear to me why 1+x_0 is regular and not a unit.  You might have a trick that helps.)

**Comment by dyunov** [comment]
In the IN construction I:
(1) mixed up sides (however for disproving right Ikeda-Nakayama one could use the "alternative convention" of writing $x$'s on the left);
(2) by the paragraph just before the properties spoiler, implied that $I = r(T x_0 x_1)$ — actually even $r(x_0 x_1)$ — does not contain any elements with nonzero constant term, since all elements of $I$ are right zero divisors. (Isn't it just $x_2 T + x_{-1} T$, by the way?)

$1 + x_0$ is regular because it has nonzero constant term. Let $t \in T$ be its inverse.
**Claim 3: $t \in R$.** Again for grading reasons $t$ cannot contain a term $\tau$ with $x^k$, $k \ge 1$ (else in the product $(1+x_0) t$, there would have been a nonzero term $1 \cdot \tau$ with $R$-grade less than all other terms $R$-proportional to $x^k$).
**Claim 4: $t \in \Bbb Q[x_0]$.** Suppose otherwise. Define a $\Bbb Q$-algebra endomorphism $\phi$ of $R$ by $x_k \mapsto x_{2k}$. Then $\phi$ fixes $1$ and $1 + x_0$, but not $t$.
Now use the description of units in polynomial rings.

As for anti-automorphic and lift/rad, these should indeed be disregarded, not sure what I was thinking about when writing them, especially about $\sigma$.

**Comment by rschwiebert** [comment]
Your observation that we can say $x_0R\cap x_1x_2R=\{0\}$ enables me to say the ring is not right uniform, and with all the other properties it implies $R$ is not dual or Ikeda-Nakayama on the right.

You've convinced me about the cohopfian thing as well: very nice!
