### ISSUE TITLE
Ring 107 (the field of hyperreal numbers) needs a description

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#19]
https://github.com/rschwiebert/dart_data/blob/785b8987539e1a37eb8da2c64bd4e7729ffd163b/db/ringapp/ring/RING_000107/data.yaml#L3

Needs a good description, or possibly its expanded details page.

**Comment by dyunov** [comment]
The ideal in $\Bbb R^{\Bbb N}$ can apparently be taken as any maximal ideal that contains the ideal of cofinite sequences (links: [1](https://math.stackexchange.com/questions/315768/how-to-create-the-set-of-hyperreal-numbers-using-ultraproduct), [2](https://en.wikipedia.org/wiki/Hyperreal_number#The_ultrapower_construction), [3](https://math.stackexchange.com/questions/1838272/why-do-we-need-ultrafilter-for-construction-of-hyperreal-numbers)).

**Comment by rschwiebert** [comment]
@dyunov  THis is ok, I think?

Let $S=\prod_{i\in \mathbb N}$, and let $T$ be the ideal of sequences of finite support. Select a maximal ideal $M$ of $S$ containing $T$. The hyperreals can be realized as the quotient ring $R=S/T$.

**Comment by dyunov** [comment]
Yes, looks fine!
