### ISSUE TITLE
Several properties of C([0,1])

### ISSUE THREAD

**Issue by guillermo-s-p** [rschwiebert/dart_data#2]
[Ring_130___C_0_1_.pdf](https://github.com/rschwiebert/dart_data/files/9316688/Ring_130___C_0_1_.pdf)
This is a list of properties of the ring C([0,1]) that do not appear on the DaRT.

**Comment by rschwiebert** [comment]
Hello: nice to meet you, and thank you for this work. 

To try to set expectations, it could be as long as a week before can process issues, simply because life and work are busy :)  I hope that does not discourage anyone like yourself!  Ultimately they will be checked out and in all likelihood adopted.

**Comment by guillermo-s-p** [comment]
Hi, thanks for your message. I understand that this could take some time, but we have been working on this for weeks, so a couple of days won't hurt! Please let me know if there is anything you need from me.

**Comment by rschwiebert** [comment]
Preliminary results are good for this: the database agrees with the consistency of the additions.  If everything goes in, there are an additional 12 deductions beyond those.

Reviewing your pdf with an eye for what to include in the 'reason' fields for each new addition.

**Comment by rschwiebert** [comment]
Very good work on this writeup.  Let me share some brief notes.  They contain improvements which I hope you might consider including in a revision of your PDF for sharing here.

1. not Jacobson: interesting!  I had not realized that each prime ideal of this ring can only lie in one maximal ideal.
2. not a V-ring: in fact, I did have logic to do this in the database. if you unpack LOG_000373 it says commutative V-rings and commutative von Neumann regular rings are the same thing. However, a quirk I was heretofore unaware of prevented both the previous deduction software (and my second version too!) from seeing the deduction applied in this case!  Nice job exposing a subtle bug!
3. Not cohopfian: nice, we can go even a step further and identify the full set of zero divisors. An element here is a zero divisor iff it is zero on a nonempty open interval in [0,1].
4. Not stable range 1:  fantastic, I did not know this property of stable-range-1 rings. And considering how much trouble i have reasoning about stable-range-1, this is going to be a great tool to eliminate that condition.  I have a mind to introduce the unique generator condition as a property in its own right, even though this is my first time seeing it.
5. Not uniform: what you've written suggests an example that's easier to type: 

`Let A be the set of functions supported on [0,0.5) and B be the set of functions supported on (0.5,1].  It's clear they are nontrivial submodules with trivial intersection, and that all their members are 0 at 0.5.  This shows the ring is not uniform.`

I think you can then comment that with any family of nonoverlapping open intervals in [0,1], you can define an ideal per interval by selecting the functions which are supported on that interval only.  Using this, you can get an infinite direct sum of ideals (say by choosing intervals [0,1/2), (1/2,1/3),(1/3,1/4)...) and you have then proven this ring **does not even have finite uniform dimension** (which implies it is not uniform.)
6. Not ikeda-nakayama:  using the revised suggested A, B above, you can see that ann(A)=B and ann(B)=A, and the observation that all elements are 0 at 1/2 makes your argument complete again.

misc: on page 5 there's reference to Theorem 10, which I think means Theorem 7 as labeled in the paper. If you're using references in latex it should be able to handle this numbering gracefully :)

Next step for me is populating this into the database to make it available.  You'll see a PR linked to this issue when that happens.

**Comment by guillermo-s-p** [comment]
Thanks for your comments and suggestions! I will work on a revised PDF and share it here
