### ISSUE TITLE
Some properties of ring 112 (the quotient of free Q-algebra on 2 elements by square of generator)

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#26]
- [x] ✔ anti-automorphic (+involutive). The map reverses the order of monomials.
- [x] :x: fully semiprime. $R/(a) = \Bbb Q[b]$ is not fully semiprime.
- [x] ✔ prime. If $c,d\not = 0$, then $cbd$ is also not $0$ (the pair of the longest words in $c$ and $d$ can't cancel with anything else).
- [x] ✔ semiprimitive. $1 + brb$ is never invertible unless $r = 0$.
- [x] :x: stable range 1. $b + y(1-b^2)$ is never invertible.
- [x] ✔ ACC annihilator. An element of form $q + ra + sb$ ($q \in \Bbb Q$, $r,s \in R$) can be a left zero divisor only if $q$, $s$ are zero (consider the longest and the shortest words). Then its right annihilator is $aR$.
- [x] :x: Noetherian. $aR \subset aR + baR \subset aR + baR + b^2 aR \ldots$
~~- [ ] :x: Bezout. $aR + baR$ is not cyclic.~~ I don't have a proof.
~~- [ ] ✔ Ikeda-Nakayama. A left annihilator can be either $0, Ra$, or $R$.~~ **Incorrect.**
- [x] :x: Ore ring. $aS \cap bR = 0$ (even $aR \cap bR = 0	$).
- [x] :x: cohopfian. $b$ is neither a unit nor a zero divisor.
- [x] :x: distributive. $K = (I + J) \cap K \not = I \cap K + J \cap K = 0$, where $I = (a+b)R$, $J = (a-b)R$, $K = aR$.
- [x] :x: uniform. See Ore ring.

Comments
---
~~Why is $R_{112}$ semiprime (property 11)? The database contains no explanation, and neither it does for the Armendariz condition. Maybe these are trivial (but not enough trivial for me).~~
Is allprops.svg generated using an automated tool? If yes, could you please update it (it does not contain a few recently added properties)?

**Comment by dyunov** [comment]
Nevermind about the "unexplained" properties, I must be blind.

**Comment by rschwiebert** [comment]
The graphs are, at present, modified by hand.  They do need to be updated.  It would be really awesome to get that completely automated, but it presents some challenges.  https://github.com/rschwiebert/RingApp/issues/59

**Comment by rschwiebert** [comment]
We need to look into a contradiction above.  I found the reason that it is not right or left uniform plausible; however when I supplied that, it was deduced that it is NOT Ikeda-Nakayama.  The logic recorded said

```
Logic (rings) 458: \(NOT "CS" on the left\) <=== \(NOT "uniform" on the left\) AND \( "strongly connected" \).
Logic (rings) 157: \(NOT "quasi-continuous" on the left\) <=== \(NOT "CS" on the left\).
Logic (rings) 158: \(NOT "Ikeda-Nakayama" on the left\) <=== \(NOT "quasi-continuous" on the left\).
```
