### ISSUE TITLE
Ring proposal: Exterior (Grassmann) algebra of a $\Bbb Q$-vector space with a countable basis

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#27]
This is an important [classical](https://www.jstor.org/stable/1996643) example of a PI-ring where the basis of identities is known explicitly (it is the identity $[[x,y],z]$). I did not find it in DaRT.

Description
---
The algebra $\Bbb Q \langle e_1, e_2, \ldots \rangle/ (\{e_i e_j + e_j e_i: i,j \in \Bbb N \})$.

Properties
---
First see your own answer about $J(R)$ [here](https://math.stackexchange.com/questions/2523700/jacobson-radical-of-an-exterior-algebra).

- [x] ✔ countable.
- [x] :x: T-nilpotent radical. Take the generators.
- [x] ✔ top simple Artinian. $R/J(R) \cong \Bbb Q$.
- [x] ✔ nil radical.
- [x] ✔ local.
- [x] ✔ strongly $\pi$-regular. Local + nil radical means it only has units and nilpotents, and both types stabilize the chain. (Not sure if this rule is in the logic.)
- [x] :x: von Neumann regular. $e_1 R e_1 = 0$.
- [x] :x: SI. Denote $\alpha e_{n_1} \ldots e_{n_k} \in J(R)$ by $\alpha \cdot n_1 \ldots n_k$ if $\alpha \not = 1$ and as $n_1 \ldots n_k$ if $\alpha = 1$. Then $(123+1256)(456+34) = 2\cdot 123456;$ $(456+34)(123+1256) = 0$; furthermore, $(456+34)7(123+1256) = 2\cdot 1234567$.
- [x] :x: semiprime. $e_1 R$ has nilpotency index $2$.
- [x] ✔ strongly connected.
- [x] ✔ quasi-duo. There is only one maximal right ideal.
- [x] :x: L/R Rickart. Too few idempotents.
- [x] :x: L/R ACC/DCC annihilator. Take the products of $e_i$'s.
- [x] ✔ L/R uniform. If $a \in K_R \le I_R$, take the shortest monomial term in $a$ and form a monomial product $P$ of $e_i$'s that occur only in other terms of $a$. Then $aP$ has a single monomial term. Similarly for $b \in L_R \le I_R$ we get $Q$. Then LCM of $aP$ and $bQ$ lies in $K_R \cap L_R$.
- [x] ✔ L/R CS. Same argument as above.
- [x] ✔ polynomial identity. The commutators only have terms of even length, so they are central.

Remarks
---
I hope there are no mistakes in my calculations for the reversible/SI conditions.
A definition of T-nilpotency on the corresponding property page might be useful.
I'm seeing the definition of uniform modules for the first time and have very little experience with essential submodules (it likely shows...)

**Comment by rschwiebert** [comment]
Local + nil radical -> strongly π regular : it wasn't in the logic, and is pretty obvious! Nice catch.

**Comment by rschwiebert** [comment]
@dyunov  Sorry, what do you mean by SI? simple-injective? self-injective? V-ring?  I actually don't recognize what the evidence is showing.

**Comment by dyunov** [comment]
"semicommutative (SI condition, zero-insertive)"

**Comment by rschwiebert** [comment]
Thanks! I believe the computations are fine. Moreover it's pretty clear to me it is 2-primal.

**Comment by rschwiebert** [comment]
Just now realizing how the definition of right T-nilpotency has the sequence of products going the opposite way I thought it did.  I should review to see if there are any errors in the db based on this...
