### ISSUE TITLE
Some additions related to the McCoy property

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#29]
Camillo, Nielsen, *[McCoy rings and zero-divisors](https://www.sciencedirect.com/science/article/pii/S0022404907001594)* (2008)
---

> Corollary 10.3: simple rings with non-trivial idempotents are never McCoy.

This logical rule applies to 5 rings, including matrix algebras $R_{11}$ and $R_{12}$ (this completes their current property list).

> Theorem 4.4: $R_i$ right McCoy $\Leftrightarrow \prod R_i$ right McCoy.

Catches $R_{152}$. The ring is BTW also polynomial identity, involutive and anti-automorphic (transpose the matrices in both components).

> The final diagram: L/R McCoy implies Dedekind finite.

Currently DaRT has 4 rings known to be non-Dedekind finite (one of these is $R_{58}$ which is already not McCoy by Corollary 10.3).

Ying, Chen, Lei, *[Extensions of McCoy Rings](https://arxiv.org/abs/0708.1789)* (2007)
---
> Theorem 2.2: $M_n(R)$ and $T_n(R)$ are never McCoy for $n > 1$.

Their proof seems to generalize to all `triangular ring`s where the bimodule $M$ is itself a unital ring.
Furthermore, it can be easily adapted for infinite matrices (see case $n>2$), which seems to kill $R_{44}$, $R_{70}$ (and $R_{80}$, $R_{81}$, $R_{82}$), $R_{15}$, $R_{93}$, (possibly $R_{142}$ if the Kronecker product analogy works), $R_{67}$, $R_{83}$.

> Theorem 3.8: passes to polynomial (not power series!) rings.

Remarks
---
- Is it possible to add invisible text behind the icons for Ctrl+F'ing on a ring page? I'd rather use ASCII `v`, `x` and `?` than Unicode for that.
- Am I right in that "**stable** under products" means the double-sided implication, while "**passes** to (subrings/quotients/...)" is only one-sided? What about the one-sided implications for products? "Involutive" and "anti-automorphic" seem to pass to products if I'm not mistaken again, but it's not obvious whether they pass to factors or not.
- Theorems 3.3, 3.4 in the arXiv paper give idea for another metaproperty with a confusing name: "passes to **rings of** quotients" (the noncommutative version of "passes to localizations"). Or its approximate converse: "passes to orders".
- McCoyness of constructions similar to $R_{38}$ and $R_{110}$ is also mentioned in Proposition 3.5 of the arXiv paper.
- Are the metaproperties involved in logic?
- "Passes to polynomial rings"/"to power series rings" is not marked on the "commutative" property. (Not that it isn't obvious.)
- In [Construction 3](https://ringtheory.herokuapp.com/rings/ring/82/expanded-details/) of $R_{82}$ "For each $a \in R$" needs to be replaced with "For each $x \in R$", and $\phi$ in the penultimate paragraph with $\psi$.
- In $R_{125}$ and $R_{44}$, something fishy goes on with the ordinals; isn't the matrix in $R_{44}$ indexed by $\omega$?

**Comment by rschwiebert** [comment]
@dyunov  I am reading this right that "a simple ring with nontrivial idempotents is never McCoy" means it's not McCoy on _both_ sides because they give these elements that work as counterexamples on both sides?

**Comment by rschwiebert** [comment]
@dyunov  Do you know a powerseries ring over a mccoy ring that's not mccoy?

**Comment by dyunov** [comment]
I think Cor10.3 of Camillo — Nielsen refers to Th10.1, and the proof shows the ring to be not right McCoy, independently of the left condition.
For the second question, Pr3.2 and 3.3 in the same paper :-)

**Comment by rschwiebert** [comment]
> For the second question, Pr3.2 and 3.3 in the same paper :-)

Oh boy, this one looks tricky. But coming from Camillo and Nielsen I think it's a good bet. Probably going to wind up as a new addition.
