### ISSUE TITLE
Commutative rings and related properties, I

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#31]
-  In a subdirect product $\prod D_i$ of domains, the annihilators are of form $\prod A_i$, where $A_i$ is either $0$ or the whole $D_i$. This implies L/R Rickart. For commutative domains, this catches $R_{151}$, $R_{104}$, $R_{105}$, $R_{96}$, $R_{95}$.
- [x] No rings in the database have been marked as complete DVR's so far!
$R_{27}$ and $R_{84}$ are easily shown to be such (mentioned even on [Wikipedia](https://en.wikipedia.org/wiki/Discrete_valuation_ring#Topology)).
On the other hand, $\Bbb Z_{(p)} \subset R_{160} \subset \Bbb Z_p = \overline{\Bbb Z_{(p)}}$ (proper inclusions), so it can't be complete.
$R_{129}$ and $R_{137}$ are similarly proper subrings of $\Bbb F[[x]]$ that contain $\Bbb F[x]$ for some fields $\Bbb F$.
-  #41

Other remarks
---
- Why is the characteristic 0 property only defined for fields (it would be useful for noncommutative rings too)?
- [x] Why is $P_{67}$ (L/R Bezout) not stable under products (according to the database, $R_{57}$ is Bezout)?

**Comment by rschwiebert** [comment]
> Why is the characteristic 0 property only defined for fields (it would be useful for noncommutative rings too)?

Originally it was added to be part of the logic "characteristic 0 field -> perfect field".  It also probably predates the switch to souffle. Nowadays I'd probably program this as "is a ring with property field and dimension "characteristic=0" ". 

Really "finite" and "countable" could be handled as dimensions only, but i like having them as proeprties since I think people will search on them a lot... I'm not sure a property callled "characteristic 0" would get a lot of use, but maybe! 

> Why is (L/R Bezout) not stable under products (according to the database,  is Bezout)? 

You're absolutely right and this is now fixed. (it DOES have that metaproperty, and the bad counterexample was removed.)

**Comment by rschwiebert** [comment]
@dyunov  Regarding your first bullet:  I fully buy your argument that a direct product of domains is Rickart. To me it even looks like an arbitrary direct product of right Rickart is right Rickart. (What do you think?)

I don't quite follow though why a subdirect product of domains would be right Rickart, though. I see what elements of $\prod R_i$ would annihilate an element of $R$, but it's not obvious to me that the idempotent generating that set would necessarily be contained in $R$ if $R$ is merely a subdirect product. Is there an argument I'm missing?

**Comment by dyunov** [comment]
You're right, my claim "This implies..." seems to be false for arbitrary subdirect products.
Though for the unitized direct sums of domains (and $R_{95}$, $R_{96}$) this hasty generalization works fine: a zero divisor has finite support, so there is an idempotent $f$ with the same support, and we just take $1-f$. Right Rickart does seem to pass to direct products.
What do you think about $R_{129}$ and $R_{137}$? (This question seems to be the most important one in this issue :-) )

**Comment by rschwiebert** [comment]
> a zero divisor has finite support

I don't think that's true. If you just take the identity $e_i$ of one of the rings then $1-e_i$ is a zero divisor with infinite support.  But still believe you're right that these particular rings happen to be Rickart.

There are basically two cases for an element $x\in R$:
1. $x$ has finite support (implying the tail is zero), whence the annihilator has cofinite support, generated by an idempotent of cofinite support (which thankfully is in $R$.)
2. The "tail" of $x$ is nonzero, and the annihilator is of finite support, generated by an idempotent of finite support.

I'm not sure about 129 and 137!  I will investigate...

In the meantime:
- [ ] Add stable under products metaproperty for the Rickart property
- [ ] mark 94, 95, 104 and 105 as rickart

**Comment by rschwiebert** [comment]
I wrote a quick utility to check for differences, and indeed there is none between 129 and 137 at present.

**Comment by dyunov** [comment]
Of course... You're right. Then as a compensation for my mistakes I'd like to note that:
- [ ] $R_{95}$ and $R_{96}$ aren't Baer: the annihilator of the subset $e_1, e_3, e_5, \ldots$ is not principal;
- [ ] $R_{151}$ is Rickart because it is a subring of $\Bbb R \times \prod \Bbb Q_p$ that contains all idempotents by definition.

**Comment by dyunov** [comment]
" $R_{160}$ is not a complete DVR" from the OP did not make it to the site.
