### ISSUE TITLE
Superficial observations on Bergman's compressible ring 86

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#36]
Description
---
I think there is a typo in the DaRT ring description: $E_{pq} \in M_2(D)$ should be $E_{pq} \in D$ (see (12) in Bergman's paper).

Claim 1. The domain $k[t]\langle X_{pq} | p, q = 0, 2\rangle$ is not commutative.
---
![image](https://github.com/rschwiebert/dart_data/assets/89836711/ea7e828c-6df8-4a5b-895f-ccba6322f15e)
Here $\not = 0$ is interpreted as "the entries are nonzero elements of $K$", where $K$ is is the field of rational functions in 17 variables.

The fact that there are no zero divisors in the rings related to this example is (not proved but) explained by the fact that the 4 generator matrices are "set in stone", i.e. the transpose of $X_{00}$ does not exist in the ring.

Claim 2 (block matrix inversion). For a $2\times 2$-block matrix <img src="https://github.com/rschwiebert/dart_data/assets/89836711/fbfa9acd-4a3d-4e7a-8b39-14d08523a38e" height="40"> over a commutative ring we have <img src="https://github.com/rschwiebert/dart_data/assets/89836711/e77967aa-b90d-4d77-bd7d-b04d5a13af1b" height="60">, where $F = (D - C A^{-1}B)^{-1}$ (if everything that *should* be invertible, *is*).
---
By [Wikipedia](https://en.wikipedia.org/wiki/Block_matrix#Block_matrix_inversion) (or by authority: Horn and Johnson paragraph 0.7.3). This establishes that $E_{pq}$'s are indeed in $D$.
Then <img src="https://github.com/rschwiebert/dart_data/assets/89836711/10a9dde6-6af9-44a3-943c-41169dd25508" height="60">.
By inspection we get that the $k$-algebra $R_{86}$ is actually generated by the subset $\\{E_{02}, E_{20}, tE_{02}, tE_{20}\\}$!

---
By the above, one only needs to check whether $FC$ and $A^{-1}B$ commute. I'd rather check $(FC)^{-1}$ and $A^{-1} B$. Indeed, by substituting $F^{-1} = D - C A^{-1} B$ and a direct calculation one gets (Lie commutator, as above) $[A^{-1} B, C^{-1} F^{-1}] = [A^{-1} B, C^{-1} D]$, this is easily proven to be nonzero by matrix specialization.

Properties
---
- [x] ❔ countable. Speaking of specialization, would you like to set $k = \Bbb Q$?
- [x] :x: commutative. 
- [x] ✔ polynomial identity. By (13), this is a subring of $M_2(K)$.
- [x] ✔ Ore domain. By (12), it embeds into $D$.
- [x] ✔ involutive. See Remark on p7.

Properties
---
- The rings of generic matrices are apparently an important object in PI theory. Some context about them is in Aljadeff—Giambruno—Procesi—Regev AMS Colloquium Publications 66 *"Rings with polynomial identities and finite dimensional representations of algebras"* p95 starting from 3.3.4.1 (they use $\Bbb Z$ instead of Bergman's $k$). However I don't see "purely ring-theoretic" results there that could help in filling the database. (Not that I understand anything in their homological algebra arguments...)

**Comment by rschwiebert** [comment]
@dyunov Embedding into a division ring alone is not sufficient for being right Ore: a domain $R$ has to be essential as a right submodule of $D_R$ for it to be right Ore.
