### ISSUE TITLE
HSP metaproperties, I

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#38]
For the most part, this list was written "unconsciously" — by comparing the DaRT property lists against each other. I never write L/R here but always mean the one-sided non-symmetric properties.
I think now that the "variety of rings" = HSP metaproperty suggestion is not that necessary on DaRT. It's unlikely there are a lot of them.
H = passes to Homomorphic images (quotients); S = passes to Subrings; P = passes to (arbitrary) Products.

General observations
---
1. $J(\prod R_i) = \prod J(R_i)$, as $r \in J(\prod R_i) \Leftrightarrow \forall x,y\\!\\!: 1 + xry$ is invertible $\Leftrightarrow \forall x,y\\!\\!:$ every projection of $1 + xry$ is invertible $\Leftrightarrow$ every projection is in $J(R_i)$.
2. By Lam II p4 (1.5), homomorphic **pre**images of IBN rings are IBN.

HSP metaproperties
---
- [x] All "domain" properties **EXCEPT Goldman, uniserial and valuation** ($h$-local, Bezout, Dedekind, Euclidean, GCD, Krull, Mori, Ore, Prüfer, Schreier, almost Dedekind, almost maximal, atomic, plain domains, normal, PID, UFD) are ❌ H, as $\Bbb Z$ is all of these and has non-domain quotients.
- [x] Goldman, uniserial, valuation domain ❌ H: $k[[x]]/(x^2)$ is not a domain.
- [x] The following "domain" properties are ❌ S because of $\Bbb Z[x] \subset \Bbb Q(x)$: $h$-local, Bezout, Dedekind, Euclidean, Goldman, Prüfer, almost Dedekind, almost maximal, PID, uniserial, valuation. Same goes for the corresponding "ring" properties: Bezout, almost maximal, PIR, uniserial, valuation (**not** normal!)
- [x] domain ✔ S.
- [x] GCD/Schreier domain ❌ S, $\Bbb C$ and $R_{77}$.
- [x] Krull/Mori/atomic domain/UFD; ACC principal ❌ S $R_{36}$ in $R_7$.
- [x] normal domain ❌ S $R_{64}$ in $k[[x]]$.
- [x] All "field" properties are ✔ H, as the image of a field is isomorphic to itself.
- [x] All "field" properties are ❌ S. $\Bbb R$ satisfies every "field" property except "algebraically" or "quadratically closed", $\Bbb C$ satisfies these two, and both contain $\Bbb Z$.
- [x] All "domain" and "field" properties are ❌ P.

- [x] Abelian ✔ S; ✔ P.
- [x] Artinian ✔ H by [standard argument](https://math.stackexchange.com/questions/4025289).
- [x] $\pi$-regular, Kasch, V ring ❌ S, $\Bbb Q \supset \Bbb Z$.
- [x] Dedekind finite ✔ S; ✔ P.
- [x] Boolean: this is clearly a variety of rings.
- [x] Bezout ✔ P by correspondence.
- [x] #44
- [x] Noetherian ✔ H.
- [x] V ring ✔ H Tuganbaev "Rings close to regular" 4.22.2 p184: "It is directly verified that all factor rings of a right V-ring are right V-rings".
- [x] PCI ✔ H. From your [MSE post](https://math.stackexchange.com/questions/2162915/pci-ring-which-is-not-semisimple) I learnt about Faith-Cozzens. Simple rings have no factors, and semisimple is ✔ H.
- [x] ACC/DCC annihilator, ACC principal, Frobenius, Goldie, Gorenstein, Grothendieck, Henselian local, Nagata, N-1, Japanese, Kasch, PCI, Noetherian ❌ P, $R_{57} = \prod F_2$.
- [x] Rickart ❌ S $R_{44}$ in $R_{15}$; ✔ P same as Baer, I think... (construct the idempotent componentwise)
- [x] NI ✔ S [Lemma 1.3(5)](https://koreascience.kr/article/JAKO201107049669172.pdf); ✔ P.
-  #46

Other metaproperties
---
moved to #45

**Comment by rschwiebert** [comment]
@dyunov 
> But maybe adding info on subrings and quotients (and products??!) would be a better way to go.

Say a little more? There's a feature now to discuss arbitrary subsets, but I'm not sure if that's what you mean.  I did toy with the idea in the past of having some table expressing relations between rings like "subring of", "factor ring of", "morita equivalent to" or something like that.

**Comment by dyunov** [comment]
I had in mind something similar to your latter description. I think there should be a separate table (or list) for each applicable metaproperty.
Say, the one for "is a subring of" relation might, among others, contain these rows:

| Ring | Subrings |
| ---- | -------- |
| 2 | 1 |
| 152 | 12 |
| X | 4 |
| 4 | X |

(where $X$ is the number of $\Bbb C(x)$ --- it does not exist in DaRT :-) )

For transitive relations it would be useful if the logic engine automatically computed the transitive closure of the user input: "Morita invariant", "passes to matrix rings/subrings/quotient rings", "stable under finite products/products", "passes to $eRe$ for any idempotent $e$", "passes to finitely generated algebras over the ring" [<-- does this mean only commutative algebras?], "forms an equational class", maybe some other ones.

There are some serious drawbacks with this approach; e.g. some of ring constructions are not specialized, and we don't really have transitivity: the system would either not know about $\Bbb Q(x) \supset k[x]$ (and be useless), or have baloney like $\Bbb Q(x) \supset k[x] \supset \Bbb F_p$.

Maybe [modal logic/Kripke semantics](https://en.wikipedia.org/wiki/Kripke_semantics#Semantics_of_modal_logic) would help? Can the involved software work with it?

Some data duplication is also, I fear, unavoidable, but it is less of a concern.

**Comment by rschwiebert** [comment]
> For transitive relations it would be useful if the logic engine automatically computed the transitive closure of the user input

It's not automatic in the sense it runs after every addition, but I do run a program to compute the closure whenever metaproperties are updated.  Including an example can't easily automatable.

> Maybe [modal logic/Kripke semantics](https://en.wikipedia.org/wiki/Kripke_semantics#Semantics_of_modal_logic) would help? Can the involved software work with it?

Huh, this is the first time I've heard of that. Here are some examples of how souffle works (that's the language I use for automated deduction.)

**Comment by dyunov** [comment]
> It's not automatic in the sense it runs after every addition, but I do run a program to compute the closure whenever metaproperties are updated.

Yes, I just meant that if we add some $\Bbb Q$-algebra $R_{2024}$ to DaRT and manually add an entry `2024 | 2`, the system would "recognize" that the subrings of $\Bbb Q$ (rings $n_1, n_2, \ldots$) are in $R_{2024}$ too, and generate rows `2024 | n_1`, `2024 | n_2`, ...
By "automatically" I meant "with minimal human intervention".

> Including an example isn't easily automatable.

This is not disputable, but (as you can see) quite a lot of metaproperties have trivial counterexamples, noticing and adding them one by one is a chore. Just the inclusion $\Bbb Z \subset \Bbb Q$ kills "passes to subring" for `72` properties. The automatic tool would fill a large portion of metaproperty entries, and then humans will have to think about the remaining interesting ones. In this issue I was mainly doing the work of such a tool, with only a few original examples and paper references:

> For the most part, this list was written "unconsciously" — by comparing the DaRT property lists against each other.

**Comment by rschwiebert** [comment]
The "NI stable under products" is an interesting one. No doubt it is stable for finite products, but it seems like the infinite product case is slipperier. I'm going to defer the infinite one for later.

**Comment by dyunov** [comment]
1) My mistake, again! The infinite one doesn't hold, take $R = \prod\limits_{i = 1}^\infty R_{44}$, $a = (E_{12}, E_{12} + E_{34}, E_{12} + E_{34} + E_{56}, \ldots)$, $b = (E_{23}, E_{23} + E_{45}, E_{23} + E_{45} + E_{67}, \ldots)$. Both are square-zero, but their sum has Jordan blocks of arbitrary lengths as projections.
2) Got it, thanks! Then... a free $k$-algebra is always IBN, and every $k$-algebra, including say $R_{15}$, is a quotient of some free $k$-algebra.
3) Suppose $S \subset R$ and $l_S(S_1) \subsetneq l_S(S_2) \subsetneq \ldots$, where $S_i \subset S$. But then the chain $l_R(S_1) \subsetneq l_R(S_2) \subsetneq \ldots$ in $R$ does not stabilize, since $\varnothing \not = (l_S(S_{k+1}) \setminus l_S(S_k)) \subset (l_R(S_{k+1}) \setminus l_R(S_k))$.
