### ISSUE TITLE
Several properties of the group ring Q[Q]

### ISSUE THREAD

**Issue by guillermo-s-p** [rschwiebert/dart_data#4]
[Ring_117___Q_Q_.pdf](https://github.com/rschwiebert/dart_data/files/9316715/Ring_117___Q_Q_.pdf)
Here is a list of properties of the ring Q[Q] that do not appear on the DaRT website. I imagine there might be theorems already built in the database regarding some of the implications that are mentioned, but I list them nonetheless for completeness.

**Comment by rschwiebert** [comment]
Another general LaTeX comment: to get the quotations to work right, you need to enclose with double tics on the left and double single-quotes on the right, like this ` ``quoted material'' `

Can you define "separative" for me? I can't seem to find it online and I don't have access to the paper.

**Comment by rschwiebert** [comment]
From your discussion of why it isn't an $I_0$ ring, we can extract a better piece of logic to add: a strongly connected I_0 ring is local.

**Comment by guillermo-s-p** [comment]
I quote from the referenced paper: "For the case in which F has characteristic 0 it is shown that FS is semiprimitive if and only if S is 'separative' in the sense of Hewitt and Zuckerman, that is, if and only if $\forall x,y\in S, x^2=xy=y^2\Rightarrow x=y$" (here $FS$ is the algebra of a commutative semigroup $S$ over a field $F$ of characteristic 0). "In particular, it follows that if $F$ has characteristic 0 and $S$ is cancellative then $FS$ is semiprimitive". I do realize that this is more than needed because any abelian group satisfies this.

The extract above is referencing "The $l_1$-algebra of a commutative semigroup" by Hewitt and Zuckerman.

**Comment by guillermo-s-p** [comment]
Thanks for your comments these past few days! I am very happy to have contributed to the website. It seems like it has led to filling quite a few gaps!
