### ISSUE TITLE
Rings that are not weakly clean

### ISSUE THREAD

**Issue by guillermo-s-p** [rschwiebert/dart_data#5]
[Property_53___Weakly_clean.pdf](https://github.com/rschwiebert/dart_data/files/9316720/Property_53___Weakly_clean.pdf)
Here is a list of counterexamples showing that some rings are not weakly clean; these are all together because they are constructed in similar ways.

**Comment by rschwiebert** [comment]
The underlying strategy is this:  in a strongly connected ring, if there is an element $x$ such that $xR\neq R$ and $x-1$ is not a unit, then $x$ is not weakly clean.  For as you noted there are two cases when there are only two idempotents: $x-u\in xR$ or $x-1=u$ for some unit.  But $x-u\in xR$ implies $u\in xR$: this is ruled out by hypothesis. So is $x-1=u$. 

In fact, if you have a ring for which $x-1$ is a unit for every nonunit $x$, you have a local ring. Putting it together we have a new logic to add:  strongly-connected + weakly clean -> local.
