### ISSUE TITLE
Ring relationships: subrings, I

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#50]
<p align="center">To untimely deceased $k[x]$, $k$ countable</p>

This issue is first of a series related to rschwiebert/RingApp#63 . Here I'll post various connections between rings (for now, this is mainly supposed to be used for detecting metaproperty failures). Raw data seems too bulky to look well on a webpage, so my initial choice would be an [OpenOffice spreadsheet*](https://github.com/rschwiebert/dart_data/files/14113186/subring_honestv1.ods).

[Here](https://github.com/rschwiebert/dart_data/files/14113378/dart_allringsv1.pdf) is a full list of DaRT rings with descriptions ordered by number, it was very useful while compiling the batch and so would be for checking it.

---
`*` The word "honest" is related to generic rings, basically it means that the ring inclusion falls under 0. in [the code](https://github.com/rschwiebert/RingApp/issues/63#issuecomment-1915740876) (and cannot hinder subring inclusion transitivity).
An inclusion of generic rings can also fall into category 0., as it was with $R_7$ and $R_{98}$ (though this specific batch contains no generic rings).

Comments
---
- Would it be possible to make a separate keyword list page (with definitions)?
- Could you please explain why you specialized $R_7$? I still think it is possible to manage RingApp#63 while having generic rings.
- Old idea: I would also suggest a **fourth** symbol for properties (maybe an exclamation mark?) that would mean "depends on the specialization". Though not sure if it is needed in many places. With respect to logic it would be just an ❔.

**Comment by rschwiebert** [comment]
I'm a bit worried that there may be gotchas if generic $k$'s are retained in some places. Over time I'm drifting toward more concrete descriptions.  The problem I foresee this may itself cause is the necessity for having rings that are similar in many ways (like Q[x] and R[x]) but I hope that will not often happen.

I do like OpenOffice but unfortunately it looks like they do not have a supported version for my laptop's OS.  Can you export your document to csv maybe?

**Comment by rschwiebert** [comment]
Thanks for finding those typos. As for rings 4 and 5... I have zero idea why the determinant conditions were in there.

Rather than needing  "depends on specialization" I would prefer to go down the path of specializing for concreteness.   I think it's going to make our lives simpler.

**Comment by dyunov** [comment]
[subring_honestv1.csv](https://github.com/rschwiebert/dart_data/files/14152482/subring_honestv1.csv)

**Comment by rschwiebert** [comment]
I haven't checked: did you generate these relationships based on your
submissions for subrings?

**Comment by dyunov** [comment]
No, these were done by visual inspection from scratch.

**Comment by rschwiebert** [comment]
I think it will be interesting to propagate properties using
metaproperties.  I think you were headed that way with your souffle snippet.

I'm leaning towards not *storing* the transitive closure of relations,
though.  I don't think i want to ever display the complete list of subrings
or homomorphic preimages or whatnot. At best maybe I'd display the
immediate predecessors or successors for each such relation.  If that's the
case we could just store a leaner Hasse diagram for it and when souffle
needs to it can generate the transitive closure for the purposes of its
computation.

It would be awesome to have all sorts of logic entries that mix everything,
metaproperties, dimensions, other properties and so on, with all the rings
involved. I might try that out, but the main thing is that the *explain*
procedure really slows things down.  It takes like 2 minutes for a single
ring to boot up an *explain session* to show the proofs it used.  If there
were many more logics and many more rings at play it would take forever.
That's what keeps stuff apart at the moment.

I wonder if I lumped everything together and just left out the explain
stuff how fast it would run...

**Comment by dyunov** [comment]
I was more concerned with finding counterexamples to metaproperties; propagation can also work, it won't be really useful for H and S metaproperties, but for polynomial rings/localizations/... it might be.

**Comment by dyunov** [comment]
Adding information from this CSV table to the local database via admin tools, will then export it and make a PR.
By the way, what's $S$ in the description of $R_{145}$? Is it the same as $D$?

**Comment by rschwiebert** [comment]
Maybe we should have a long term ticket to track minor typos?
