### ISSUE TITLE
Metaproperties that *are* inherited by quotients, III

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#53]
Obvious
---
- [x] countable.
- [x] finite.
- [x] semisimple. From Wedderburn-Artin.
- [x] simple. No nontrivial quotients.

Right ideal correspondence theorem
---
- [x] distributive. If $I_k$ are right $R$-ideals that contain $I$, and $J_k = I_k/I$, then $J_1 \cap (J_2 + J_3) = \dfrac{I_1 \cap (I_2 + I_3)}{I} = \dfrac{(I_1 \cap I_2) + (I_1 \cap I_3)}{I} = (J_1 \cap J_2) + (J_1 \cap J_3)$ as $R$-modules, and therefore as $R/I$-modules.
- [x] duo, quasi-duo. The correspondence respects two-sided ideals.
- [x] fully prime, fully semiprime. These were discussed before.
- [x] local. The quotient inherits only one single maximal right ideal.
- [x] principal ideal ring. Take the images of the generators.
- [x] serial, uniserial. Direct application.
-  semi-Noetherian. Direct application.  (RS: I think you may have hit a pitfall. Given an $I$, you have no way of knowing if $T/I < R/I$ has a maximal submodule: it could be that the only maximal submodule you can come up with for $T$ does not contain $I$.  If true, I don't think it's very simple.)
-  semilocal. E.g. by [this](https://math.stackexchange.com/questions/1122163) (also a direct application).  (RS: How? I believe the thing you link to requires $I\subseteq J(R)$.)

The quotient map is a homomorphism
---
- [x] periodic.
- [x] polynomial identity.
- [x] exchange.  <s>(RS: This is not obvious to me...)</s>
-  semicommutative. (RS: This must be mistaken: $k\langle x,y\rangle$ is semicommutative but $k\langle x,y\rangle/(xy-1)$ is not

Remarks
---
- Inspired by a comment about the dimensions and sides in the RingApp source code: Lam I p235 Ex14.1 and 14.2 give examples of nonequal L/R dimensions over a field; does DaRT need them?
- Does there exist a semi-Artinian but not semi-Noetherian ring? For self-injective rings DaRT's logic rules this out.

**Comment by rschwiebert** [comment]
> Does there exist a semi-Artinian but not semi-Noetherian ring?

We know for sure 
`ring is commutative AND ring is semi-Artinian on the right -->  ring is max ring on the right`

I think I never got around to evaluating if Theorem 3.1 of 

Năstăsescu, Constantin, and Nicolae Popescu. "Anneaux semi-artiniens." Bulletin de la Société mathématique de France 96 (1968): 357-368.

Is or is not saying that a two-sided semi-Artinian ring is two-sided max. They do not seem to require commutativity, nor do they include left/right modifiers for the statement.

**Comment by rschwiebert** [comment]
Yes, "condition H" is the same as "max ring" which is the "logical dual" to semi-artinian.  "Semi-noetherian" is somehow less well-behaved. Perhaps there's a chance that semi-Artinian implies R_R is seminoetherian as a module.

**Comment by rschwiebert** [comment]
I started with $\bar a + \bar b = \bar 1$, and continued with $a+b+i=1$ and got $ar+(b+i)s=1$, and I was looking for $\overline{bs}$ to be idempotent, but made some mistake in computation. After sleeping things are working: if you expand $((b+i)s)^2=(b+i)s$ you get something that says $(bs)^2=bs$ mod $I$. 👍
