### ISSUE TITLE
Morita invariance, I

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#59]
The following Morita invariant properties from your [edits](https://en.wikipedia.org/w/index.php?title=Morita_equivalence&diff=396155977&oldid=394521589) on Wikipedia are not marked as such in DaRT:
- [x] simple
- [x] semihereditary
- [x] hereditary
- [x] nonsingular
- [x] coherent
- [x] semiprimary
- [x] perfect
- [x] semiperfect
- [x] semilocal

Specialization of $R_{11}$ and $R_{12}$ would help with negative metaproperties.

**Comment by rschwiebert** [comment]
The ones I don't have negative examples/relations for:

- [ ] Frobenius
- [ ] Goldie
- [ ] IBN
