### ISSUE TITLE
Prime ring with nonzero nil Jacobson radical

### ISSUE THREAD

**Issue by dyunov** [rschwiebert/dart_data#66]
Description
---
> Let $A_n = T_{2^n}(\Bbb Q)$. The ring is the direct limit of the system $\{A_k| k = 1, 2, \ldots\}$ with respect to the homomorphisms $\sigma_n$: $A_n \hookrightarrow A_{n+1}$, $A \mapsto A \oplus A$.
Notes: a prime ring with nonzero nil radical.

This ring is Ex1.2 from ["Structure and topological conditions of NI rings"](https://www.sciencedirect.com/science/article/pii/S002186930600158X) by Hwang, Jeon, Lee (2006). In Ex1.3 they use an arbitrary domain instead of $\Bbb Q$ (and in some papers that use this construction they need characteristic 2, but not here).
This is clearly a subring of $RCFM(\Bbb Q)$ (as $2^k$-periodic block diagonal matrices) and, in turn, of $R_{15}$; but also of the ring in suggestion #65.

The units are again the elements with nonzero numbers on the diagonal (because it is so in $A_n$'s), the Jacobson radical is everything above diagonal. It is nil but not nilpotent.

Properties
---
- [x] :heavy_check_mark: countable.
- [x] :heavy_check_mark: prime. Pr1.3 p188 in the paper.
- [x] :heavy_check_mark: NI. Pr1.1.
- [x] :x: 2-primal. Ex1.2.
- [x] :x: left/right T-nilpotent radical. In the block diagonal representation, take the sequence of $2^k$-Jordan blocks $\Bbb J_k = \sum\limits_{i = 0}^\infty \sum\limits_{j = 1}^{2^k-1} e_{2^k i + j, 2^k i + j + 1}$. Right multiplication by a new block just shifts the nonzero elements to the right; left multiplication, upwards. Since $2^n \gg n$, the products never vanish (for right multiplication, the first row is nonzero, and for left, the rightmost column).
- [x] :x: orthogonally finite. $e_{11} + e_{33} + e_{55} + \ldots$; $e_{22} + e_{66} + e_{10,10} + \ldots$, $e_{44} + e_{12,12} + e_{20,20} + \ldots$; $\ldots$
- [x] :x: fully semiprime. $J(R)$ is not idempotent.
- [x] :heavy_check_mark: semiregular. Each $T_{2^n}(\Bbb Q)$ is.
- [x] :heavy_check_mark: strongly $\pi$-regular. This is true for every $T_{2^n}$, and $x^k R = (x^k T_{2^n}) R$. (In other words, I think that this property passes to arbitrary direct limits.)
- [x] :x: nonzero left socle. Let $M = Ra$. Then, for a large enough Jordan block $\Bbb J = \Bbb J_{2^n}$, $R \Bbb J a$ is a nonzero submodule of $M$ that does not contain $a$. Thus $M$ is not simple.
- [x] :x: nonzero right socle. Ditto $M = aR$.
- [x] :x: semilocal. $R/J(R)$ is not even orthogonally finite, cf. above.
- [x] :x: top simple. ...and neither it is simple, there is an ideal $(e_{11} + e_{33} + \ldots) R/J(R)$.
- [x] :heavy_check_mark: compressible. Since all $T_{2^n}$'s have trivial centers, the claim follows from my next comment on compressibility of $T_n(k)$.

**Comment by rschwiebert** [comment]
I plan on adding this in conjunction with another direct limit of matrix rings based on the whole partial order of divisibility (instead of just the chain selected here.)  I'm waiting to chat with my advisor who I believe used such a ring in his dissertation.
