### ISSUE TITLE
Matrix rings

### ISSUE THREAD

**Issue by lenaread** [rschwiebert/dart_data#7]
Attached are properties of matrix rings that do not appear on DaRT grouped by the ring. The first pdf Matrix ring properties acts as a contents for the others.

[Matrix_ring_properties.pdf](https://github.com/rschwiebert/dart_data/files/9352748/Matrix_ring_properties.pdf)
[Osofsky_s_32_element_ring.pdf](https://github.com/rschwiebert/dart_data/files/9352749/Osofsky_s_32_element_ring.pdf)
[Right_not_left_Artinian_triangular_ring.pdf](https://github.com/rschwiebert/dart_data/files/9352750/Right_not_left_Artinian_triangular_ring.pdf)
[Right_not_left_nonsingular_ring.pdf](https://github.com/rschwiebert/dart_data/files/9352751/Right_not_left_nonsingular_ring.pdf)
[T_2_F_2_.pdf](https://github.com/rschwiebert/dart_data/files/9352752/T_2_F_2_.pdf)
[T_n_F_.pdf](https://github.com/rschwiebert/dart_data/files/9352753/T_n_F_.pdf)
[Varadarajan_s_left_not_right_cohopfian_ring.pdf](https://github.com/rschwiebert/dart_data/files/9352754/Varadarajan_s_left_not_right_cohopfian_ring.pdf)

**Comment by rschwiebert** [comment]
I'm slowly making my way through this one.

@lenaread Can you remind me how complement right ideals are defined again? I can't seem to find a source and most sources seem to omit it.

**Comment by rschwiebert** [comment]
Ah!  I found it in again in Lectures on Modules and Rings. Never mind! A complement to a submodule $N$ is just another submodule maximal with respect to having trivial intersection with $N$.

**Comment by rschwiebert** [comment]
In the "ore ring" suggestions, I notice that you've only checked one of the Ore conditions (permutability) but there is a second one (reversibility).   Perhaps it works out as well, I just haven't checked them yet.
